Add script to execute scripts

diff --git a/bin/script b/bin/script
--- a/bin/script
+++ b/bin/script
@@ -7,41 +7,31 @@ help() {
     echo "script [service] [script]"
     echo
     echo To execute a script on a service the service must be running.
-    echo The script to execute is 
+    echo These are the services and scripts that can be run:
+
+    find ./scripts -maxdepth 1 -mindepth 1 -type d | sort | while read script_dir; do
+        echo
+        echo $(basename $script_dir)
+
+        find $script_dir -maxdepth 1 -mindepth 1 -type f | sort | while read script_file; do
+            echo "  - $(basename $script_file)"
+        done
+    done
 }
 
-case "$service" in
-"" | "--help" | "-h")
-    help
-    ;;
-"redis")
-    # hack a snazzy redis prompt despite it being a stock image
-    docker-compose exec --env SUDO_USER=x --env SUDO_PS1=x --env PS1="{^_^} redis\n      \w % " redis bash
-    ;;
-"website")
-    docker-compose exec --env SUDO_USER=x --env SUDO_PS1=x --env PS1="{^_^} website\n      \w % " website /bin/bash
-    ;;
-"rails")
-    docker-compose exec website /bin/bash '-c' 'bundle exec rails console'
-    ;;
-"tmux")
-    docker-compose exec website overmind 'c' 'server'
-    ;;
-"mysql")
-    docker-compose exec mysql mysql -ppassword
-    ;;
-"redis-cli")
-    docker-compose exec redis redis-cli
-    ;;
-"tooling-invoker")
-    docker-compose exec --env PS1="{^_^} tooling-invoker\n      \w % " tooling-invoker /bin/bash
-    ;;
-"tooling-orchestrator")
-    docker-compose exec --env PS1="{^_^} tooling-orchestrator\n      \w % " tooling-orchestrator /bin/sh
-    ;;
-esac
+run_script() {
+    script_path="./scripts/$service/$script"
 
+    if [ ! -f $script_path ]; then
+        echo "Could not find the '$script' script for the '$service' service."
+        exit 1
+    fi
 
+    # Excute the script
+    $script_path
+
+    handle_container_error
+}
 
 handle_container_error() {
     result=$?
@@ -54,3 +44,12 @@ handle_container_error() {
         exit $result
     fi
 }
+
+case "$service" in
+"" | "--help" | "-h")
+    help
+    ;;
+*)
+    run_script
+    ;;
+esac
